#!/usr/bin/env python3
"""Generate the CV and resume from the website's _config.yml.

_config.yml is the single source of truth: the header comes from `name`,
`positions`, `email`, `url` and `social`; the body from `experiences`,
`honors`, `service`, `talks`, `references` and `papers`; and the order of
sections from the `cv_layout` and `resume_layout` blocks. cv.tex and resume.tex only pick
the document class and include what this script writes.

Nothing written here is committed; the GitHub Pages workflow runs this
script before compiling. Locally:

    python3 _cv/build.py [path/to/_config.yml] && cd _cv && latexmk -pdf cv.tex resume.tex

Writes into _cv/generated/:
    cv-preamble.tex, cv-body.tex          the CV
    resume-preamble.tex, resume-body.tex  the resume
    refs.bib                              every paper and event as BibTeX
    headshot.jpg                          the website photo, downscaled
"""
import html
import re
import sys
from pathlib import Path
from urllib.parse import urlparse

import yaml
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
OUT = Path(__file__).resolve().parent / "generated"
HEADER = "% Generated by _cv/build.py from _config.yml -- do not edit.\n"
LINK_LABELS = ["pdf", "html", "code", "data", "video", "slides", "poster"]
JOURNAL_HINTS = ["Journal", "Review", "Behavior", "Systems 38", "Research Part"]

SHORT_VENUES = [  # resume one-liners use the names people say out loud
    ("Advances in Neural Information Processing Systems", "NeurIPS"),
    ("Conference on Neural Information Processing Systems", "NeurIPS"),
    ("ICML Workshop on AI for Science", "ICML AI for Science Workshop"),
    ("International Conference on Machine Learning", "ICML"),
    ("ACM Conference on Fairness, Accountability, and Transparency", "ACM FAccT"),
    ("ACM Conference on Economics and Computation", "ACM EC"),
    ("ACM Conference on Recommender Systems", "ACM RecSys"),
    ("ACM Symposium on Computer Science and Law", "ACM CSLAW"),
    ("American Economic Review", "AER"),
    ("Journal of the American Statistical Association", "JASA"),
    ("Autonomous Agents and Multi-Agent Systems", "JAAMAS"),
    ("Journal of Online Trust and Safety", "JOTS"),
    ("Symposium on the Foundations of Responsible Computing", "FORC"),
    ("Web and Internet Economics", "WINE"),
    ("Allied Social Science Associations Meeting", "ASSA"),
    ("Princeton University Press", "Princeton UP"),
    ("Stanford Digital Economy Lab", "Stanford DEL"),
    ("Weeklong seminar, Villigst Foundation", "Villigst Foundation"),
    ("MIT AI Ethics and Policy Group", "MIT AI Ethics & Policy"),
]

CONTACT_ICONS = {
    "email": r"\faEnvelope[regular]", "url": r"\faGlobeAmericas",
    "google": r"\faGraduationCap", "github": r"\faGithub",
    "linkedin": r"\faLinkedin", "twitter": r"\faTwitter", "facebook": r"\faFacebook",
}

LATEX_ESCAPES = {"&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#", "_": r"\_",
                 "~": r"\textasciitilde{}", "^": r"\textasciicircum{}"}


# ------------------------------------------------------------------ text

def escape(text):
    return "".join(LATEX_ESCAPES.get(c, c) for c in str(text))


def url_tex(url):
    """Escape a URL for \\href inside macro arguments."""
    if url.startswith("/"):
        url = "https://andyhaupt.com" + url
    return url.replace("\\", "").replace("%", r"\%").replace("#", r"\#")


def quotes(text):
    """Turn straight double quotes into TeX quotes."""
    return re.sub(r'"([^"]*)"', r"``\1''", text)


def html_to_latex(text, br=r"\newline "):
    """Convert the small HTML subset used in _config.yml to LaTeX."""
    text = html.unescape(str(text or ""))
    links = []

    def stash(m):
        links.append((m.group(1), m.group(2)))
        return f"\x00{len(links) - 1}\x00"

    text = re.sub(r'<a href="([^"]*)"[^>]*>(.*?)</a>', stash, text)
    for tag, mark in (("b", "\x01"), ("i", "\x05"), ("em", "\x05")):
        text = text.replace(f"<{tag}>", mark).replace(f"</{tag}>", "\x02")
    text = text.replace("<sup>‡</sup>", "\x03").replace("<br>", "\x04")
    text = re.sub(r"<[^>]+>", "", text)
    text = quotes(escape(text))
    text = (text.replace("\x01", r"\me{").replace("\x05", r"\emph{")
                .replace("\x02", "}").replace("\x03", r"\eq{}").replace("\x04", br))
    for i, (url, label) in enumerate(links):
        text = text.replace(f"\x00{i}\x00", rf"\href{{{url_tex(url)}}}{{{html_to_latex(label)}}}")
    return text.replace("‡", r"\eq{}")


def strip_markdown_links(text):
    return re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", text)


def plain(text):
    """Strip HTML and equal-contribution markers (for BibTeX)."""
    return re.sub(r"<[^>]+>", "", html.unescape(str(text or ""))).replace("‡", "").strip()


def years(time, short=False):
    """'Aug 2026-Aug 2027' -> '2026--2027'; '2017-19' -> '2017--2019' (or '2017--19')."""
    found = re.findall(r"\d{4}|(?<=-)\d{2}\b", str(time))
    if not found:
        return escape(time)
    start, end = found[0], found[-1]
    if len(end) == 2:
        end = start[:2] + end
    if start == end:
        return start
    return f"{start}--{end[2:] if short else end}"


def short_institution(name):
    return re.sub(r"\s*University\s*|University of\s*", "", name).strip() or name


# ---------------------------------------------------------------- papers

def surname(name):
    return name.strip().split()[-1].replace(".", "")


def bib_key(paper, used):
    people = plain(paper.get("authors") or paper.get("organizers") or "Haupt")
    first = re.sub(r"[^a-z]", "", surname(people.split(",")[0]).lower()) or "haupt"
    word = next((w for w in re.findall(r"[A-Za-z]+", paper["title"].lower())
                 if w not in {"a", "an", "the", "of", "on", "for", "and",
                              "position", "to", "in", "by"}), "untitled")
    key = base = f"{first}{str(paper['date'])[:4]}{word}"
    n = 1
    while key in used:
        n += 1
        key = f"{base}{n}"
    used.add(key)
    return key


def coauthors(paper):
    """'with Hitzig' / 'with Gemp et al.' for one-line resume entries."""
    people = [p.strip() for p in
              plain(paper.get("authors") or paper.get("organizers", "")).split(",")]
    others = [surname(p) for p in people if p and "Haupt" not in p and p != "et al."]
    if not others:
        return ""
    if len(others) <= 2:
        return "with " + " and ".join(others)
    return f"with {others[0]} et al."


def split_venue(venue):
    """'Advances in NeurIPS (Position Paper), 2026.' -> (name, note)."""
    v = re.sub(r",?\s*(?:\w+\s)?\d{4}\.?$", "", plain(venue)).rstrip(". ")
    note = ""
    m = re.search(r"\s*\(([^)]*[A-Za-z][^)]*)\)\s*$", v)
    if m:
        note, v = m.group(1), v[: m.start()]
    return v.strip(), note


def short_venue(paper):
    """'Games and Economic Behavior 148, p. 415-426' -> 'Games and Economic Behavior'."""
    venue, note = split_venue(paper["venue"])
    venue = re.sub(r"^SSRN Preprint \d+$", "SSRN", venue)
    venue = re.sub(r" \d+(?: \(\d+\))?(?:, p\. [\d-]+)?$", "", venue)
    for long, short in SHORT_VENUES:
        if venue.startswith(long):
            if venue[len(long):].strip():  # e.g. a speaker list: its parentheses are no note
                note = ""
            venue = short
            break
    note = note.replace("Evaluations and Datasets Track", "E&D Track")
    return f"{venue} ({note})" if note else venue


def paper_url(paper):
    return paper.get("html") or paper.get("pdf") or ""


def cvpub(paper):
    people = paper.get("authors")
    if people is None:
        people = "Organizers: " + paper.get("organizers", "")
    buttons = "".join(rf"\cvbutton{{{label.upper()}}}{{{url_tex(paper[label])}}}"
                      for label in LINK_LABELS if paper.get(label))
    tags = "".join(rf"\cvtag{{{escape(t)}}}" for t in paper.get("tags", []))
    return (rf"\cvpub{{{quotes(escape(paper['title']))}}}{{{html_to_latex(people)}}}"
            rf"{{{html_to_latex(paper['venue'])}}}{{{escape(paper['type'])}}}"
            rf"{{{tags}}}{{{buttons}}}")


def publine(paper):
    title = paper.get("short_title") or paper["title"]
    return (rf"\cvpubline{{{str(paper['date'])[:4]}}}{{{quotes(escape(title))}}}"
            rf"{{{escape(short_venue(paper))}}}{{{coauthors(paper)}}}"
            rf"{{{url_tex(paper_url(paper))}}}")


def bibtex(paper, key):
    people = paper.get("authors") or paper.get("organizers", "")
    authors = [a.strip() for a in plain(people).split(",") if a.strip()]
    authors = ["others" if a == "et al." else a for a in authors]
    fields = {"title": "{" + paper["title"] + "}", "author": " and ".join(authors),
              "year": str(paper["date"])[:4]}
    venue, note = split_venue(paper["venue"])
    kind = "misc"
    if paper["type"] == "Thesis":
        kind = "phdthesis" if "Ph.D." in venue else "mastersthesis"
        degree, _, school = venue.partition(", ")
        fields["school"] = school
        if kind == "mastersthesis":
            fields["type"] = degree
    elif "Press" in venue:
        kind = "book"
        fields["publisher"] = venue
        note = note or "forthcoming"
    elif paper["type"] in ("Published", "Preprint") and not venue.startswith(("Preprint", "SSRN")):
        if any(h in venue for h in JOURNAL_HINTS):
            kind = "article"
            m = re.match(r"(.+?) (\d+)(?: \((\d+)\))?(?:, p\. ([\d-]+))?$", venue)
            if m:
                fields["journal"], fields["volume"] = m.group(1), m.group(2)
                if m.group(3):
                    fields["number"] = m.group(3)
                if m.group(4):
                    fields["pages"] = m.group(4).replace("-", "--")
            else:
                fields["journal"] = venue
        else:
            kind = "inproceedings"
            fields["booktitle"] = venue
    else:
        fields["howpublished"] = venue or paper["type"]
        if paper["type"] == "Event":
            note = "Organized event"
    if note:
        fields["note"] = note
    url = paper_url(paper)
    if url and not url.startswith("/"):
        fields["url"] = url
    doi = re.search(r"(10\.\d{4,}/[^\s\"]+)", url)
    if doi and "arxiv" not in url:
        fields["doi"] = doi.group(1).split("?")[0]
    body = ",\n".join(f"  {k} = {{{v}}}" for k, v in fields.items() if v)
    return f"@{kind}{{{key},\n{body}\n}}\n"


# --------------------------------------------------------------- sections

class Renderer:
    """Renders one document (mode 'cv' or 'resume') from the config."""

    def __init__(self, config, mode):
        self.config, self.mode = config, mode
        self.layout = config[f"{mode}_layout"]
        self.resume = mode == "resume"

    # header ---------------------------------------------------------------
    def preamble(self):
        c = self.config
        lines = [rf"\cvname{{{escape(c['name'])}}}",
                 rf"\cvdoctype{{{escape(self.layout['title'])}}}",
                 r"\cvphoto{generated/headshot.jpg}"]
        lines += [rf"\cvposition{{{escape(p['title'])}, {escape(p['employer'])}}}"
                  for p in c.get("positions", [])]
        for key in self.layout.get("contacts", []):
            if key == "email":
                url = c["email"]
                label = url.removeprefix("mailto:")
            elif key == "url":
                url = c["url"]
                label = urlparse(url).netloc.removeprefix("www.")
            else:
                url = c["social"][key]
                label = "Scholar" if key == "google" else url.rstrip("/").rsplit("/", 1)[-1]
            lines.append(rf"\cvcontact{{{CONTACT_ICONS[key]}}}{{{url_tex(url)}}}{{{escape(label)}}}")
        lines.append(rf"\hypersetup{{pdftitle={{{escape(c['name'])} -- "
                     rf"{escape(self.layout['title'])}}},pdfauthor={{{escape(c['name'])}}}}}")
        return HEADER + "\n".join(lines) + "\n"

    def body(self):
        c = self.config
        research = escape(strip_markdown_links(c["research"]))
        intro = f"I study {research}."
        out = [r"\makecvheader", (rf"{{\small {intro}}}" if self.resume else intro), ""]
        for section in self.layout["sections"]:
            content = section["content"]
            out.append(rf"\section{{{escape(section['title'])}}}")
            if content == "papers":
                out.append(self.papers(section))
            elif content in ("references", "honors", "service", "talks", "rows"):
                out.append(getattr(self, content)(section))
            else:
                groups = content if isinstance(content, list) else [content]
                out.append(self.experiences(groups, section.get("selected")))
            out.append("")
        return HEADER + "\n".join(out)

    # experiences ------------------------------------------------------------
    def experiences(self, groups, selected=False):
        out = []
        for e in self.config["experiences"]:
            if e.get("cv_section") not in groups:
                continue
            if selected and not e.get("resume"):
                continue
            short = e.get("resume") if self.resume else {}
            short = short if isinstance(short, dict) else {}
            title = short.get("title") or e.get("degree") or e["title"]
            title = escape(plain(str(title).replace("<br>", "; ")))
            if self.resume:  # compact: resume overrides, and only the resume wording
                e = {**e, **short, "description": short.get("description", ""),
                     "cv_details": []}
            else:
                e = {**e, "description": e.get("cv_description", e.get("description", ""))}
            if e.get("style") == "line":
                text = rf"\textbf{{{escape(e['place'])}}}, {title}"
                if e["description"]:
                    text += ": " + html_to_latex(e["description"], br="; ")
                out.append(rf"\cvitem{{{years(e['time'])}}}{{{text}}}")
                continue
            details = html_to_latex(e["description"])
            if e.get("cv_details"):
                items = "".join(rf"\item {html_to_latex(d)} " for d in e["cv_details"])
                details += rf"\begin{{itemize}}{items}\end{{itemize}}"
            out.append(rf"\cventry{{{years(e['time'])}}}{{{escape(e['place'])}}}"
                       rf"{{{url_tex(e.get('url', ''))}}}{{{title}}}{{{details}}}")
        return "\n".join(out)

    # lists ------------------------------------------------------------------
    def honors(self, section):
        return "\n".join(rf"\cvitem{{{years(h['year'])}}}{{{html_to_latex(h['title'])}}}"
                         for h in self.config.get("honors", []))

    def service(self, section):
        return "\n".join(rf"\cvitem{{{years(s['years'])}}}{{{html_to_latex(s['title'])}}}"
                         for s in self.config.get("service", []))

    def talks(self, section):
        return "\n".join(rf"\cvitem{{{years(t['year'])}}}{{{escape(t['venues'])}}}"
                         for t in self.config.get("talks", []))

    def references(self, section):
        refs = self.config.get("references", [])
        if self.resume:
            fields = list(dict.fromkeys(r["field"] for r in refs))
            return "\n".join(
                rf"\cvitem{{{escape(f)}}}{{" + ", ".join(
                    f"{escape(r['name'])} ({escape(short_institution(r['institution']))})"
                    for r in refs if r["field"] == f) + "}"
                for f in fields)
        cells = [rf"\cvreference{{{escape(r['name'])}}}{{{escape(r['title'])}}}"
                 rf"{{{escape(r['institution'])}}}{{{escape(r['email'])}}}" for r in refs]
        rows = [r"\hfill".join(cells[i:i + 3]) for i in range(0, len(cells), 3)]
        return (r"\begin{minipage}{\linewidth}" + "\n"
                + "\n\\par\\vspace{2ex}\n".join(rows) + "\n" + r"\end{minipage}")

    def rows(self, section):
        out = []
        for row in section["rows"]:
            items = row.get("text") or self.summary(row["content"], row.get("selected"))
            out.append(rf"\cvitem{{{escape(row['label'])}}}{{{items}}}")
        return "\n".join(out)

    def summary(self, content, selected=False):
        """Honors, service or events as one '; '-joined line for the resume.

        With `selected`, only items marked `resume: true` are listed."""
        if content == "events":
            events = [p for p in self.config["papers"] if p["type"] == "Event"
                      and (p.get("resume") or not selected)]
            return ", ".join(
                f"{escape(p.get('short_title') or p['title'])} "
                f"({escape(short_venue(p))} {str(p['date'])[:4]})" for p in events)
        if content == "honors":
            items, when = self.config.get("honors", []), "year"
        elif content == "service":
            items, when = self.config.get("service", []), "years"
        else:
            raise ValueError(f"unknown resume row content {content!r}")
        items = [i for i in items if i.get("resume") or not selected]
        return "; ".join(f"{html_to_latex(i.get('short') or i['title'])} ({years(i[when], True)})"
                         for i in items)

    # papers -----------------------------------------------------------------
    def papers(self, section):
        """Papers of the section's types (with `selected`, only those marked
        `resume: true`; with `merged`, interleaved by date instead of grouped
        by type); the resume uses one line each."""
        out = []
        headings = self.layout.get("type_headings", {})
        types = section.get("types", [])
        if section.get("merged"):  # one date-ordered list across the types
            types = [tuple(types)]
        for i, kind in enumerate(types):
            kinds = kind if isinstance(kind, tuple) else (kind,)
            if "Published" in kinds:
                note = (r"\eq{} indicates equal contribution or alphabetical author order."
                        if not self.resume else
                        "With co-authors in parentheses.")
                out.append(rf"{{\small\color{{muted}}{note}}}\par\vspace{{1ex}}")
            if i and kind in headings:
                out.append(rf"\cvsubsection{{{escape(headings[kind])}}}")
            render = publine if self.resume else cvpub
            out += [render(p) for p in self.config["papers"] if p["type"] in kinds
                    and (p.get("resume") or not section.get("selected"))]
        return "\n".join(out)


def main():
    source = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "_config.yml"
    if not source.exists():
        sys.exit(f"{source} not found; pass the website's _config.yml as an argument")
    config = yaml.safe_load(source.read_text())
    OUT.mkdir(exist_ok=True)
    for mode in ("cv", "resume"):
        renderer = Renderer(config, mode)
        (OUT / f"{mode}-preamble.tex").write_text(renderer.preamble())
        (OUT / f"{mode}-body.tex").write_text(renderer.body())
    used = set()
    bib = [bibtex(p, bib_key(p, used)) for p in config["papers"]]
    (OUT / "refs.bib").write_text(HEADER + "\n" + "\n".join(bib))
    photo = source.parent / config.get("profile_pic", "")
    if photo.is_file():
        with Image.open(photo) as im:
            im.convert("RGB").resize((500, 500), Image.LANCZOS).save(
                OUT / "headshot.jpg", quality=88, optimize=True)
    print(f"wrote {OUT}: CV, resume, {len(bib)} BibTeX records", file=sys.stderr)


if __name__ == "__main__":
    main()
